<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUh3RZFA\srcApp_KernelLocalDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUh3RZFA/srcApp_KernelLocalDebugContainer.php') {
    touch(__DIR__.'/ContainerUh3RZFA.legacy');

    return;
}

if (!\class_exists(srcApp_KernelLocalDebugContainer::class, false)) {
    \class_alias(\ContainerUh3RZFA\srcApp_KernelLocalDebugContainer::class, srcApp_KernelLocalDebugContainer::class, false);
}

return new \ContainerUh3RZFA\srcApp_KernelLocalDebugContainer([
    'container.build_hash' => 'Uh3RZFA',
    'container.build_id' => 'd21089d6',
    'container.build_time' => 1618966524,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUh3RZFA');
