<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'home_page' => [[], ['_controller' => 'App\\Controller\\HomeController::home'], [], [['text', '/']], [], []],
    'espace_adherant' => [[], ['_controller' => 'App\\Controller\\HomeController::adherant'], [], [['text', '/espace-adherant']], [], []],
    'espace_employeur' => [[], ['_controller' => 'App\\Controller\\HomeController::employeur'], [], [['text', '/espace-employeur']], [], []],
    'espace_partenaire' => [[], ['_controller' => 'App\\Controller\\HomeController::partner'], [], [['text', '/espace-partenaire']], [], []],
];
