<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHysDsEu\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHysDsEu/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerHysDsEu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerHysDsEu\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerHysDsEu\srcApp_KernelProdContainer([
    'container.build_hash' => 'HysDsEu',
    'container.build_id' => '1d65c6e7',
    'container.build_time' => 1620107244,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHysDsEu');
