<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Adherant extends \App\Entity\Adherant implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'numero_soinclair', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'cartesoinclair', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'cin', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'entreprise', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'code_client', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'lastname', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'nom_conjoint_first', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'nom_conjoint_second', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'nbr_enfant', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'date_naissance', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'situation_pro', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'category_sociopro', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'maladie_chroni', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'formule_soin_clair', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'supp_one', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'supp_two', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'supp_three', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'firstname', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'phonenumber', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'subscription_date', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'expiring_date', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'demandes'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'numero_soinclair', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'cartesoinclair', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'cin', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'entreprise', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'code_client', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'lastname', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'nom_conjoint_first', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'nom_conjoint_second', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'nbr_enfant', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'date_naissance', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'situation_pro', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'category_sociopro', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'maladie_chroni', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'formule_soin_clair', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'supp_one', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'supp_two', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'supp_three', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'firstname', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'phonenumber', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'subscription_date', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'expiring_date', '' . "\0" . 'App\\Entity\\Adherant' . "\0" . 'demandes'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Adherant $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCartesoinclair(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCartesoinclair', []);

        return parent::getCartesoinclair();
    }

    /**
     * {@inheritDoc}
     */
    public function setCartesoinclair(string $cartesoinclair): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCartesoinclair', [$cartesoinclair]);

        return parent::setCartesoinclair($cartesoinclair);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroSoinclair(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroSoinclair', []);

        return parent::getNumeroSoinclair();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroSoinclair(string $numero_soinclair): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroSoinclair', [$numero_soinclair]);

        return parent::setNumeroSoinclair($numero_soinclair);
    }

    /**
     * {@inheritDoc}
     */
    public function getCin(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCin', []);

        return parent::getCin();
    }

    /**
     * {@inheritDoc}
     */
    public function setCin(string $cin): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCin', [$cin]);

        return parent::setCin($cin);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntreprise(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntreprise', []);

        return parent::getEntreprise();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntreprise(?string $entreprise): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntreprise', [$entreprise]);

        return parent::setEntreprise($entreprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeClient(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeClient', []);

        return parent::getCodeClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeClient(?string $code_client): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeClient', [$code_client]);

        return parent::setCodeClient($code_client);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastname(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastname', []);

        return parent::getLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastname(?string $lastname): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastname', [$lastname]);

        return parent::setLastname($lastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomConjointFirst(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomConjointFirst', []);

        return parent::getNomConjointFirst();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomConjointFirst(?string $nom_conjoint_first): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomConjointFirst', [$nom_conjoint_first]);

        return parent::setNomConjointFirst($nom_conjoint_first);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomConjointSecond(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomConjointSecond', []);

        return parent::getNomConjointSecond();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomConjointSecond(?string $nom_conjoint_second): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomConjointSecond', [$nom_conjoint_second]);

        return parent::setNomConjointSecond($nom_conjoint_second);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrEnfant(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrEnfant', []);

        return parent::getNbrEnfant();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrEnfant(?int $nbr_enfant): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrEnfant', [$nbr_enfant]);

        return parent::setNbrEnfant($nbr_enfant);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(?string $adresse): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissance(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissance', []);

        return parent::getDateNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissance(?\DateTimeInterface $date_naissance): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissance', [$date_naissance]);

        return parent::setDateNaissance($date_naissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getSituationPro(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSituationPro', []);

        return parent::getSituationPro();
    }

    /**
     * {@inheritDoc}
     */
    public function setSituationPro(string $situation_pro): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSituationPro', [$situation_pro]);

        return parent::setSituationPro($situation_pro);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorySociopro(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorySociopro', []);

        return parent::getCategorySociopro();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorySociopro(?string $category_sociopro): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorySociopro', [$category_sociopro]);

        return parent::setCategorySociopro($category_sociopro);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaladieChroni(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaladieChroni', []);

        return parent::getMaladieChroni();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaladieChroni(?string $maladie_chroni): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaladieChroni', [$maladie_chroni]);

        return parent::setMaladieChroni($maladie_chroni);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormuleSoinClair(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormuleSoinClair', []);

        return parent::getFormuleSoinClair();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormuleSoinClair(?string $formule_soin_clair): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormuleSoinClair', [$formule_soin_clair]);

        return parent::setFormuleSoinClair($formule_soin_clair);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuppOne(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuppOne', []);

        return parent::getSuppOne();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuppOne(?string $supp_one): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuppOne', [$supp_one]);

        return parent::setSuppOne($supp_one);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuppTwo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuppTwo', []);

        return parent::getSuppTwo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuppTwo(?string $supp_two): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuppTwo', [$supp_two]);

        return parent::setSuppTwo($supp_two);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuppThree(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuppThree', []);

        return parent::getSuppThree();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuppThree(?string $supp_three): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuppThree', [$supp_three]);

        return parent::setSuppThree($supp_three);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', []);

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname(?string $firstname): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', [$firstname]);

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhonenumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhonenumber', []);

        return parent::getPhonenumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhonenumber(?string $phonenumber): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhonenumber', [$phonenumber]);

        return parent::setPhonenumber($phonenumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille(?string $ville): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$ville]);

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubscriptionDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubscriptionDate', []);

        return parent::getSubscriptionDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubscriptionDate(?\DateTimeInterface $subscription_date): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubscriptionDate', [$subscription_date]);

        return parent::setSubscriptionDate($subscription_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpiringDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpiringDate', []);

        return parent::getExpiringDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpiringDate(?\DateTimeInterface $expiring_date): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpiringDate', [$expiring_date]);

        return parent::setExpiringDate($expiring_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDemandes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDemandes', []);

        return parent::getDemandes();
    }

    /**
     * {@inheritDoc}
     */
    public function addDemande(\App\Entity\Demande $demande): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDemande', [$demande]);

        return parent::addDemande($demande);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDemande(\App\Entity\Demande $demande): \App\Entity\Adherant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDemande', [$demande]);

        return parent::removeDemande($demande);
    }

}
