<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJkKxQSK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJkKxQSK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJkKxQSK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJkKxQSK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJkKxQSK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JkKxQSK',
    'container.build_id' => '9e6a4684',
    'container.build_time' => 1620107400,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJkKxQSK');
