<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKWjlxQ4\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKWjlxQ4/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKWjlxQ4.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKWjlxQ4\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKWjlxQ4\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KWjlxQ4',
    'container.build_id' => '2e9b33ae',
    'container.build_time' => 1620183573,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKWjlxQ4');
